export const SET_POKEMONS = "SET_POKEMONS";
export const SET_POKEMON = "SET_POKEMON";
export const SET_ADDPOKEMON = "SET_ADDPOKEMON";
export const SET_TOTALCOUNT = "SET_TOTALCOUNT";
export const SET_SNACKBAR = "SET_SNACKBAR";
export const RESET_SNACKBAR = "RESET_SNACKBAR";
export const START_LOADING = "START_LOADING";
export const FINISH_LOADING = "FINISH_LOADING";
